version: 0.1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: 5.1
  - LUA: 5.2
  - LUA: 5.3
  - LUA: luajit-2.0
  - LUA: luajit-2.1

install:
- appveyor DownloadFile https://dl.bintray.com/xpol/luavm/LuaVM-0.2.0-vs2015-x64.exe -FileName LuaVM.exe
- LuaVM.exe /verysilent /dir=C:\luavm
- call C:\luavm\luavm\luavm.cmd use %LUA%
- type C:\luavm\luavm\versions\%LUA%\luarocks.bat

build_script:
- luarocks make

before_test:
- luarocks install busted

test_script:
- busted
